permalink: pretty
title: Sampath Lab
tagline: 'A script and app collection'
url: http://sampath-lab-ucla.github.io
baseurl: ''

github:
  org: https://github.com/Sampath-Lab-UCLA

theme: jekyll-theme-minimal
